#!/usr/bin/env python
"""
Valmor F. de Almeida dealmeidav@ornl.gov; vfda

Cortix: a program for system-level modules
        coupling, execution, and analysis.

An Application object is the composition of Module objects and Network objects.

Tue Dec 10 11:21:30 EDT 2013
"""
#*********************************************************************************
import os, sys, io
import logging
from src.configtree import ConfigTree

# constructor helper
from ._application import _Application

from src.network.interface import Network
#*********************************************************************************

#*********************************************************************************
class Application(): # this is meant to be a singleton class

 def __init__( self,
               appWorkDir = None,
               appConfigNode = ConfigTree()
             ):

  _Application( self, appWorkDir, appConfigNode )

  return

#---------------------------------------------------------------------------------
# Getters

 def GetNetworks(self):
  return self.networks

 def GetNetwork(self, name):
  for net in self.networks:
     if net.GetName() == name: return net
  return None

 def GetModules(self):
  return self.modules

 def GetModule(self, name):
  for mod in self.modules:
     if mod.GetName() == name: return mod
  return None

#---------------------------------------------------------------------------------
# Setup application         

 def Setup(self):

#  for modName in self.__configNode.GetModuleNames():
   
#   module = Module( modName, self.__configNode )
#   self.__modules.append( module )

  return

#---------------------------------------------------------------------------------
# Setup network             

 def __SetupNetworks(self):

  s = 'start __SetupNetworks()'
  self.__log.debug(s)

  for netNode in self.__configNode.GetAllSubNodes('network'):

   netConfigNode = ConfigTree( netNode )
   assert netConfigNode.GetNodeName() == netNode.get('name'), 'check failed'

   network = Network( netConfigNode )

   self.__networks.append( network )

   s = 'appended network ' + netNode.get('name')
   self.__log.debug(s)

  s = 'end __SetupNetworks()'
  self.__log.debug(s)

  return

#*********************************************************************************
# Unit testing. Usage: -> python application.py
if __name__ == "__main__":
  print('Unit testing for Application')
